// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.Models;

namespace back_end.Migrations
{
    [DbContext(typeof(EquipmentContext))]
    [Migration("20211013001941_InitialContext")]
    partial class InitialContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("back_end.Models.EquipmentAsignation", b =>
                {
                    b.Property<int>("idAsigment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("allasigned")
                        .HasColumnType("int");

                    b.Property<int>("equipmentstock")
                        .HasColumnType("int");

                    b.HasKey("idAsigment");

                    b.ToTable("EquipmentAsig");
                });

            modelBuilder.Entity("back_end.Models.EquipmentDetail", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accesories")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("carctetis")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("equipmentstock")
                        .HasColumnType("int");

                    b.Property<int>("imei")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("nserie")
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("EquipmentId");

                    b.ToTable("EquipmentDetails");
                });

            modelBuilder.Entity("back_end.Models.UsersUpdate", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departament")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("direction")
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("email")
                        .HasColumnType("int");

                    b.Property<string>("nameuser")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("puesto")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("sur_maternal")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("sur_paternal")
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("dni");

                    b.ToTable("UsersUpdate");
                });
#pragma warning restore 612, 618
        }
    }
}
